backend:
  name: github
  repo: rising-winds/therisingwinds.com

media_folder: static/assets
public_folder: assets

collections:

  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: chapters
    label: Chapters
    folder: chapters
    create: true
    fields: 
      - name: title
        label: Chapter Name

      - label: Chapter Rank
        name: chapterRank
        widget: "select"
        options: ["Shire", "Barony", "Duchy", "Grand Duchy", "Principality"]
        default: "Shire"
      
      - name: Ork Url
        label: orkUrl

      - label: Parent Chapter
        name: parent
        widget: relation
        collection: chapters
        searchFields: [title]
        valueField: title
        required: false

      - label: Heraldry 
        name: heraldry
        widget: image
        media_library:
          config:
            multiple: false
     
      - name: Ork Url
        label: orkUrl

      - label: Body
        name: body
        widget: markdown

      - label: "Meetings"
        name: meetings
        widget: list
        fields: 

          - label: Meeting Type
            name: type
            widget: select
            options: ["primary", "fighterPractice", "craftNight", "other"]

          - label: Frequency
            name: frequency
            widget: select
            options: ["weekly", "biweekly", "monthly"]

          - label: Location Name
            name: locationName

          - label: Address
            name: address
            widget: text

          - label: Location
            name: location
            widget: map

      - label: "Social Media Links"
        name: socialMedia
        widget: list
        fields: 
          - label: Site
            name: type
            widget: select
            options: ["Facebook", "Twitter", "Instagram", "Discord", "Other"]

          - label: Displayed Text
            name: displayText

          - label: URL
            name: url
      
      - label: "Officers"
        name: officers
        widget: list
        fields: 

          - label: Persona Name
            name: personaName

          - label: Mundane Name
            name: mundaneName

          - label: Office Title
            name: office

          - label: Avatar 
            name: avatar
            widget: image
            media_library:
              config:
                multiple: false

  - name: events
    label: Events
    folder: events
    create: true
    fields:
      - { name: title, label: Title }
      - { name: startTime, label: "Start Time", widget: datetime}
      - { name: endTime, label: "End Time", widget: datetime}
      
      - label: Event Banner 
        name: banner
        widget: image
        media_library:
          config:
            multiple: false

      - name: links
        label: Important Links
        required: false
        widget: list
        fields: 
          - name: label
            label: Label
          - name: url
            label: Url

      - name: location
        label: Location
        widget: object
        fields: 
          - name: name
            label: Name
          - name: streetAddress
            label: Street Address
          - name: state
            label: State
          - name: zip
            label: Zip Code
      - name: gatePricing
        label: Gate Price 
        widget: list
        required: false
        fields:
          - name: label
            label: Label
          - name: price
            label: Price
            widget: number

      - name: staff
        label: Staff
        widget: list
        required: false
        fields:
          - name: personaName
            label: Persona Name
          - name: mundaneName
            label: Mundane Name
          - name: role
            label: role
          - label: Avatar 
            name: avatar
            widget: image
            media_library:
              config:
                multiple: false
                
      - name: schedule
        label: Schedule
        widget: list
        fields:
          - name: label
            label: Label
          - name: startTime
            label: Start Time
            widget: datetime
          - name: price
            label: Price
            widget: number
            required: false
          - name: description
            label: Description
            widget: markdown


