backend:
  name: github
  repo: rising-winds/therisingwinds.com

media_folder: static/assets
public_folder: assets

collections:

  - name: blog
    label: Blog
    folder: data/blog
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: chapters
    label: Chapters
    folder: data/chapters
    create: true
    fields: 
      - name: title
        label: Chapter Name

      - label: Chapter Rank
        name: chapterRank
        widget: "select"
        options: ["Shire", "Barony", "Duchy", "Grand Duchy", "Principality"]
        default: "Shire"
      
      - name: Ork Url
        label: orkUrl

      - label: Parent Chapter
        name: parent
        widget: relation
        collection: chapters
        searchFields: [title]
        valueField: title
        required: false

      - label: Heraldry 
        name: heraldry
        widget: image
        media_library:
          config:
            multiple: false
     
      - name: Ork Url
        label: orkUrl

      - label: Body
        name: body
        widget: markdown

      - label: "Meetings"
        name: meetings
        widget: list
        fields: 

          - label: Meeting Type
            name: type
            widget: select
            options: ["primary", "fighterPractice", "craftNight", "other"]

          - label: Frequency
            name: frequency
            widget: select
            options: ["weekly", "biweekly", "monthly"]

          - label: Location Name
            name: locationName

          - label: Address
            name: address
            widget: text

          - label: Location
            name: location
            widget: map

      - label: "Social Media Links"
        name: socialMedia
        widget: list
        fields: 
          - label: Site
            name: type
            widget: select
            options: ["Facebook", "Twitter", "Instagram", "Discord", "Other"]

          - label: Displayed Text
            name: displayText

          - label: URL
            name: url
      
      - label: "Officers"
        name: officers
        widget: list
        fields: 

          - label: Persona Name
            name: personaName

          - label: Mundane Name
            name: mundaneName

          - label: Office Title
            name: office

          - label: Avatar 
            name: avatar
            widget: image
            media_library:
              config:
                multiple: false

  - name: events
    label: Events
    folder: data/events
    create: true
    fields:
      - { name: title, label: Title }
      - { name: startTime, label: "Start Time", widget: datetime}
      - { name: endTime, label: "End Time", widget: datetime}
      
      - label: Event Banner 
        name: banner
        widget: image
        media_library:
          config:
            multiple: false
      - label: Host
        name: host
        widget: list
        required: false
        multiple: false
        types: 
          - label: Kingdom
            name: kingdom
            type: object
            fields:
              - label: Type
                name: type
                widget: hidden
          - label: Chapter
            name: chapter
            type: object
            fields:
              - label: Host Chapter
                name: hostChapter
                widget: relation
                collection: chapters
                searchFields: [title]
                valueField: title
                required: false
                multiple: true

      - name: links
        label: Important Links
        required: false
        widget: list
        fields: 
          - name: label
            label: Label
          - name: url
            label: Url

      - name: location
        label: Location
        widget: object
        fields: 
          - name: name
            label: Name
          - name: streetAddress
            label: Street Address
          - name: state
            label: State
          - name: zip
            label: Zip Code
      - name: gatePricing
        label: Gate Price 
        widget: list
        required: false
        fields:
          - name: label
            label: Label
          - name: price
            label: Price
            widget: number

      - name: staff
        label: Staff
        widget: list
        required: false
        fields:
          - name: personaName
            label: Persona Name
          - name: mundaneName
            label: Mundane Name
          - name: role
            label: role
          - label: Avatar 
            name: avatar
            widget: image
            media_library:
              config:
                multiple: false

      - name: schedule
        label: Schedule
        widget: list
        fields:
          - name: label
            label: Label
          - name: startTime
            label: Start Time
            widget: datetime
          - name: price
            label: Price
            widget: number
            required: false
          - name: description
            label: Description
            widget: markdown

  - name: minutes
    label: minutes
    folder: data/minutes
    identifier_field: startTime
    slug: "{{fields.meetingType}}-{{fields.startTime}}"
    fields: 

      - name: startTime
        label: Meeting Start
        widget: datetime

      - name: endTime
        label: Meeting End
        widget: datetime

      - label: Type
        name: meetingType
        widget: select
        options: ["Althing", "Board Meeting"]

      - name: meetingPoints
        label: Meeting Points
        widget: list
        types: 
          - name: attendance
            label: Board Attendance (if Board Meeting)
            type: object
            fields:
              - name: attending
                label: Attending
                widget: list
                fields:
                  - name: mundaneName
                    label: Mundane Name

                  - label: Office
                    name: boardOffice
                    widget: select
                    options: ["Board Member", "Case Analyst", "Chairperson", "Secretary", "Vice Chairperson", "Vice Secretary of Finance"]
                    default: "Board Member"
              
              - name: absent
                label: Absent
                widget: list
                fields:
                  - name: mundaneName
                    label: Mundane Name

                  - label: Office
                    name: boardOffice
                    widget: select
                    options: ["Board Member", "Case Analyst", "Chairperson", "Secretary", "Vice Chairperson", "Vice Secretary of Finance"]
                    default: "Board Member"

          - name: agendaItem
            label: Agenda Item
            type: object
            fields:
              - name: title
                label: Title
              
              - name: itemType
                label: Item Type
                widget: select
                options: ["Scheduled", 'New Business']

              - name: points
                label: Agenda Points
                widget: list
                types:

                  - name: note
                    label: Note
                    widget: object
                    fields:
                      - label: Note
                        name: note

                  - name: boardMotion
                    label: Board Motion/Vote
                    widget: object
                    fields:

                      - name: motion
                        label: Motion

                      - name: motionedBy
                        label: Motion By (Mundane Name)
                        
                      - name: secondedBy
                        label: Seconded By (Mundane Name)
                        required: false

                      - name: didVotePass
                        label: Did Vote Pass
                        widget: boolean

                      - name: yayVotes
                        label: Yay votes
                        widget: list
                        field:
                          - name: mundaneName
                            lable: Mundane Name

                      - name: nayVotes
                        label: Nay votes
                        widget: list
                        field:
                          - name: mundaneName
                            lable: Mundane Name
                      
                      - name: abstainVotes
                        label: Abstain Votes
                        widget: list
                        field:
                          - name: mundaneName
                            lable: Mundane Name

                  - name: althingMotion
                    label: Althing Motion/Vote
                    widget: object
                    fields:

                      - name: motion
                        label: Motion

                      - name: motionedBy
                        label: Motion By (Mundane Name)
                        
                      - name: secondedBy
                        label: Seconded By (Mundane Name)
                        required: false

                      - name: didVotePass
                        label: Did Vote Pass
                        widget: boolean

                      - name: yayVotes
                        label: Yay votes
                        widget: number

                      - name: nayVotes
                        label: Nay votes
                        widget: number
                      
                      - name: abstainVotes
                        label: Abstain Votes
                        widget: number



  - name: boardMembers
    label: Board Members
    folder: data/board-members
    fields:
      
      - name: mundaneName
        label: Mundane Name

      - label: Office
        name: boardOffice
        widget: select
        options: ["Board Member", "Case Analyst", "Chairperson", "Secretary", "Vice Chairperson", "Vice Secretary of Finance"]
        default: "Board Member"

      - name: bio
        label: Bio
        widget: text

      - label: Avatar 
        name: avatar
        widget: image
        media_library:
          config:
            multiple: false

  - name: kingdomOfficers
    label: Kingdom Officers
    folder: data/officers
    fields:

      - label: Persona Name
        name: personaName

      - label: Mundane Name
        name: mundaneName

      - label: Office Title
        name: office

      - name: bio
        label: Bio
        widget: text

      - label: Avatar 
        name: avatar
        widget: image
        media_library:
          config:
            multiple: false


